### PR TITLE
Print statement changed

### PR DESCRIPTION
**Pull request by Irfan367**
Please review the code @aemwaqas60

### CODE REVIEW

**Review by aemwaqas60 — COMMENTED** [review]
Please remove the console logs and white spaces. @Irfan367

**Review by aemwaqas60 — APPROVED** [review]
I have reviewed your changes now we can merge with main branch.

**Comment by shahzad-saleem-2iq** [comment]
@aemwaqas60 satisfied go ahead and merge.

**Review by aemwaqas60 — APPROVED** [review]
@shahzad-saleem-2iq I have approved this request.

**Review by aemwaqas60 — APPROVED** [review]
Re approved by Waqas.

**Pull request merged**
